name: Test AWS CDK Python Wrapper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quick-test:
    name: Quick Test on Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          python -m pip install -e .[test,dev]

      - name: Run tests
        run: |
          pytest tests/ -v

      - name: Run slow tests
        run: |
          pytest tests/ -v --slow

  full-test:
    name: Full Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    needs: quick-test
    if: ${{ success() }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
        exclude:
          - os: ubuntu-latest
            python-version: '3.10'  # Already tested in quick-test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov
          python -m pip install -e .[test,dev]

      - name: Run tests
        run: |
          pytest tests/ -v

      - name: Run slow tests
        run: |
          pytest tests/ -v --slow

  build:
    name: Build package
    runs-on: ubuntu-latest
    needs: quick-test  # Changed from full-test to quick-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel twine

      - name: Build package
        run: |
          python -m build

      - name: Check package
        run: |
          python -m twine check dist/*

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/ 